mysql周りの用意

diff --git a/JustFile b/JustFile
--- a/JustFile
+++ b/JustFile
@@ -1,4 +1,81 @@
 set dotenv-load := true
+NAME := `sed -n 2p ./Cargo.toml | cut -c 8- | xargs printf`
+VERSION := `sed -n 3p ./Cargo.toml | cut -c 11- | sed '1s/^/v/' | xargs printf`
+
+DOCKER_REPO := "nnao45"
+MYSQL_DOCKER := "jqapi-test-mysql"
+MYSQL_DOCKER_EXISTS_FLAG := `if [ ! -z ${CIRCLECI:-} ]; then echo 1; exit 0; fi; docker ps --format "{{ .Names }}" --filter "name=jqapi-test-mysql" | wc -l`
+MYSQL_VERSION := "8.0.27"
 
 hello:
   echo "Hello, world!"
+
+run:
+  cargo run
+
+build:
+  cargo build --release
+
+mysql-db-is-exist:
+    #!/bin/bash
+    echo MYSQL_DOCKER_EXISTS_FLAG is {{ MYSQL_DOCKER_EXISTS_FLAG }}
+    if [ ! {{ MYSQL_DOCKER_EXISTS_FLAG }} = 0 ]; then
+        echo "{{ MYSQL_DOCKER }} is exists"
+    else
+        echo "{{ MYSQL_DOCKER }} is not exists"
+    fi
+
+check-mysql-db:
+    #!/bin/bash
+    STATUS=1
+    COUNT=0
+
+    while [ ${STATUS} = 1 ]
+    do
+        mysqladmin ping -u root -h ${MYSQL_HOST} -p${MYSQL_PORT} > /dev/null 2>&1 && STATUS=0
+        if [ ${STATUS} = 1 ]; then
+            echo -n '.'
+        fi
+        sleep 1
+        (( COUNT++ ))
+        if [ ${COUNT} = 50 ]; then
+            echo "Sorry, Cannot connect the mysql docker."
+            exit 1
+        fi
+    done
+
+    echo '!'
+    echo {{ MYSQL_DOCKER }} is alive
+
+lunch-mysql-db:
+    #!/bin/bash
+    if [ ! {{ MYSQL_DOCKER_EXISTS_FLAG }} = 0 ]; then
+        echo "{{ MYSQL_DOCKER }} is exists. Not work."
+    else
+        echo 'set up the mysql docker'
+        docker run --name {{ MYSQL_DOCKER }} \
+            --rm \
+            -d \
+            -e MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD} \
+            -p ${MYSQL_PORT}:${MYSQL_PORT} mysql:{{ MYSQL_VERSION }} \
+            --character-set-server=utf8mb4 \
+            --default-authentication-plugin=mysql_native_password \
+            --collation-server=utf8mb4_unicode_ci
+    fi
+
+setup-mysql-db:
+    echo "CREATE DATABASE IF NOT EXISTS ${MYSQL_DB} DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci" | mysql -h${MYSQL_HOST} -uroot -p${MYSQL_PASSWORD} 2>/dev/null
+    echo 'CREATE USER '\'admin\''@'\'%\'' IDENTIFIED BY '\'${MYSQL_PASSWORD}\''' | mysql -h${MYSQL_HOST} -uroot -p${MYSQL_PASSWORD} 2>/dev/null
+    echo 'GRANT ALL On *.* To admin@'\'%\'';' | mysql -h${MYSQL_HOST} -uroot -p${MYSQL_PASSWORD} 2>/dev/null
+    echo 'set global time_zone = "Asia/Tokyo"' | mysql -h${MYSQL_HOST} -u${MYSQL_USER} -p${MYSQL_PASSWORD} 2>/dev/null
+    # diesel migration run
+
+run-mysql-db: lunch-mysql-db check-mysql-db setup-mysql-db
+
+clean-mysql-db:
+    #!/bin/bash
+    if [ {{ MYSQL_DOCKER_EXISTS_FLAG }} = 0 ]; then
+        echo "{{ MYSQL_DOCKER }} is not exists. Not work."
+    else
+        docker kill {{ MYSQL_DOCKER }} > /dev/null && echo 'clean up the mysql docker'
+    fi
